name: From Documentation

on:
  push:
    branches: [ "main" ]
    paths:
      - src/CSharp.Experiments.FromDocumentation/**
      - tests/CSharp.Experiments.FromDocumentation.Tests/**
  pull_request:
    branches: [ "main" ]
    paths:
      - src/CSharp.Experiments.FromDocumentation/**
      - tests/CSharp.Experiments.FromDocumentation.Tests/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Update Coverlet
      run: dotnet tool update -g coverlet.console
    - name: Build
      run: dotnet build --no-restore
    - name: Test and Collect Code Coverage
      run: |
        dotnet test --no-build \
          tests/CSharp.Experiments.FromDocumentation.Tests/CSharp.Experiments.FromDocumentation.Tests.csproj \
          --verbosity normal \
          /p:CollectCoverage=true \
          /p:CoverletOutputFormat=opencover
    - name: Upload Coverage Reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true
